site_name: Hey Ada
site_description: Smart voice assistant running on ESP32 with speech recognition and natural language processing
site_author: Marcin Dudek, Mateusz Basiaga
repo_url: https://github.com/zeefxd/ada-assistant-api
repo_name: ada-assistant-api

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
  - swagger-ui-tag

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - API Reference:
    - Speech-to-Text: api/stt.md
    - Text-to-Speech: api/tts.md
    - Language Model: api/llm.md
    - Command Detection: api/commands.md
  - Development:
    - Contributing: development/contributing.md